// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkers8ZERAVMXhHiK2n-aYZ2737PACk1M',
    appId: '1:860383243174:web:861c361d1be6bfe6a1fd67',
    messagingSenderId: '860383243174',
    projectId: 'my-list-1101',
    authDomain: 'my-list-1101.firebaseapp.com',
    storageBucket: 'my-list-1101.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwIOSu_2f-Nb6OUQSUO6wN1pUyMnI_uck',
    appId: '1:860383243174:android:66d14b2243241aeda1fd67',
    messagingSenderId: '860383243174',
    projectId: 'my-list-1101',
    storageBucket: 'my-list-1101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Rtbi3FuX1lNw5m3o3IrKtBDecSGdI4g',
    appId: '1:860383243174:ios:4dac36639eacc48ba1fd67',
    messagingSenderId: '860383243174',
    projectId: 'my-list-1101',
    storageBucket: 'my-list-1101.appspot.com',
    iosClientId: '860383243174-rpnqeon67mm5h0c33h1m3up8mqrq6ird.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
